@startuml

box "服务方pod"
participant 服务方进程 AS service
participant 服务方proxy AS serviceProxy
end box

participant "Control Center" AS controlCenter
participant Collector AS collector
participant Srvmgr AS srvmgr


autonumber
service -> service: 启动

serviceProxy -> serviceProxy: 启动，等待调用方通知

loop
service -> serviceProxy: 通知启动成功
end
serviceProxy -> service: ACK

serviceProxy -> controlCenter: 注册

serviceProxy -> srvmgr: 拉取初始配置（调用关系列表等）
serviceProxy -> serviceProxy: 缓存整理（多个Map）
serviceProxy -> serviceProxy: 监听端口，开始接收请求

......
service -> collector: 上报监控数据

......
serviceProxy -> collector: 上报监控数据

......
srvmgr -> controlCenter: 下发管控指令（调用关系变更、配置变更等）
controlCenter -> serviceProxy: 指令下推
serviceProxy -> serviceProxy: 指令解析与执行

......
collector -> controlCenter: 流控指令
controlCenter -> serviceProxy: 指令下推
serviceProxy -> serviceProxy: 指令解析与执行
......

@enduml